#!/bin/sh--unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1A_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1B_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1C_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1D_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1E_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1F_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1G_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1L_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1M_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1N_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1O_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme1P_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 



#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme5A_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6A_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6B_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6C_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6D_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6E_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6F_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6G_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6H_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6I_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmynondiffme6J_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --data_only --unweighted 
#jobsub_q --user nalex --unweighted 
