#!/bin/shg--unweighted 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1A_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1B_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1C_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1D_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1E_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1F_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1G_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1L_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1M_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1N_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1O_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme1P_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 

#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme5A_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme6A_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000 
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme6B_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme6C_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme6D_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme6E_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme6F_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000
#python /exp/minerva/app/users/nalex/nccoh/AL9-NCCohPi0/selection/gridSelection.py --playlist Nimmyspdiffme6G_nx --ntuple_tag fspline --use-sideband Pi0  Pi0_muonexits Diffractive Electron_Neutrino --truth --cal_POT  --mc_only --unweighted --memory 10000
#jobsub_q --user nalexg--unweighted 
